---
title: "BikeShare Project"
##"Why Do People Ride the Capital BikeShare?"
author: "Kevin Kiernan, Eric Christiansen, Ruijia Yang"
date: "12/5/2019"
output: html_document
  # ioslides_presentation:
  #   widescreen: true
runtime: shiny
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
library(ggplot2)
library(shiny)
library(dplyr)
library(tidyr)
library(leaflet)
library(geosphere)
library(sp)
library(ggmap)
library(gganimate)
```

## Ridership Since 2010
#### People don't use this service in the winter
```{r}
load("RidershipData.rds")
#monthly_counts_duration<-monthly_counts
#total_counts_duration<-total_counts

#mode_bin_duration<-which(total_counts_duration$total_counts==max(total_counts_duration$total_counts))
#median_bin_duration<-mean(monthly_counts_duration$Duration.Median)
ridership_long<-gather(ridership,'Member.rides','Casual.rides',key=Type,value=Count)
#Histogram for duration
ridership.plot<-ggplot(ridership_long,aes(x=Date,y=Count,fill=Type))+
  geom_area()+
  theme_light()

renderPlot(ridership.plot,width=1000,height=500)
```

### Trip Duration
```{r}
load("TripDurationData.rds")
monthly_counts_duration<-monthly_counts
total_counts_duration<-total_counts

mode_bin_duration<-which(total_counts_duration$total_counts==max(total_counts_duration$total_counts))
median_bin_duration<-mean(monthly_counts_duration$Duration.Median)

#Histogram for duration
full.duration.hist<-ggplot(total_counts_duration,aes(x=bins,y=total_counts))+
  geom_bar(stat='identity',color="blue",fill="light blue")+
  geom_vline(xintercept=mode_bin_duration, linetype="dotted", color="black", size=0.75)+
  geom_vline(xintercept=median_bin_duration, linetype="dotted", color="black", size=0.75)+
  annotate(geom="text", x=5, y=1800000, label="Modal Ride= 5-6 Minutes",color="black",hjust=-0.01)+
  annotate(geom="text", x=11, y=1200000, label="Median Ride= 11 Minutes",color="black",hjust=-0.01)+
  labs(title="The Modal Ride Lasts 5-6 Minutes",
       subtitle="Rideshare Data from 2010-2019",
       y="Count",
       x="Ride Duration in Minutes")+
  ylim(0,2000000)+
  theme_light()

renderPlot(full.duration.hist)
```

## Trip Distance
```{r}
load("TripDistanceData.rds")
monthly_counts_distance<-monthly_counts
total_counts_distance<-total_counts

mode_bin_distance<-which(total_counts_distance$total_counts==max(total_counts_distance$total_counts))
median_bin_distance<-mean(monthly_counts_distance$Distance.Median)

#Histogram for Distance
full.distance.hist<-ggplot(total_counts_distance,aes(x=bins,y=total_counts))+
  geom_bar(stat='identity',color="blue",fill="light blue")+
  geom_vline(xintercept=total_counts_distance$bins[mode_bin_distance], linetype="dotted", color="black", size=0.75)+
  geom_vline(xintercept=median_bin_distance, linetype="dotted", color="black", size=0.75)+
  annotate(geom="text", x=total_counts_distance$bins[mode_bin_distance], 
           y=5000000, label="Modal Ride= 1/2 Mile",color="black",hjust=-0.01)+
  annotate(geom="text", x=median_bin_distance, 
           y=4500000, label="Median Ride=3/4 Mile",color="black",hjust=-0.01)+
  labs(title="The Modal Ride is About Half a Mile",
       subtitle="Rideshare Data from 2010-2019",
       y="Count",
       x="Ride Length in Miles")+
  xlim(-0.25,5)+
  theme_light()

renderPlot(full.distance.hist)
```

## People Mostly Ride N-S and E-W
```{r}
load("TripHeadingData.rds")
monthly_counts_heading<-monthly_counts
total_counts_heading<-total_counts

#Histogram for heading
full.heading.hist<-ggplot(total_counts_heading,aes(x=bins,y=total_counts))+
  geom_bar(stat='identity',color="blue",fill="light blue")+
  labs(subtitle="Rideshare Data from 2010-2019",
       y="Count of Total Trips",
       x="Trip Heading")+
  xlim(0,360)+
  ylim(0,150000)+
  coord_polar()+
  theme_light()

renderPlot(full.heading.hist,width=800,height=800)
```


```{r,warnings=FALSE}
r_colors <- rgb(t(col2rgb(colors()) / 255))
names(r_colors) <- colors()

overall_wd<-getwd()
station.path<-paste0(overall_wd,"/Git/","Capital_Bike_Share_Locations.csv")
station.data<-read.csv(file=station.path)
station.data$TERMINAL_NUMBER<-as.factor(station.data$TERMINAL_NUMBER)
load("tallies.rds")
final.tallies$Station.ID<-as.factor(final.tallies$Station.ID)
station.data<-station.data %>% merge(final.tallies,by.x="TERMINAL_NUMBER",by.y="Station.ID") %>%
  select(TERMINAL_NUMBER,Group,LATITUDE,LONGITUDE,Total.Arrivals,Total.Departures,Flux,Total.Usage)
station.data$Group<-as.POSIXct(station.data$Group,format="%H:%M")
station.data$Direction<-ifelse(sign(station.data$Flux)>=0,"Donator Station","Receiver Station")
station.data$Flux<-abs(station.data$Flux)

usage_rank<-station.data %>% group_by(TERMINAL_NUMBER) %>% summarise(MF=max(abs(Flux)))
usage_rank<-usage_rank[order(-usage_rank$MF),]
pick.stations<-usage_rank$TERMINAL_NUMBER[1:300] #Pick the 150 most-used stations
station.data<-filter(station.data,TERMINAL_NUMBER %in% pick.stations)
rm(list=c("final.tallies","usage_rank","pick.stations"))
register_google(key="AIzaSyBwv7PRw5AE4v0DDpP10991RYli2zraFxE")

DC_map<-qmap("dc",zoom=13,maptype='toner-lite', source="stamen")

DC_map_stations<-DC_map+
  geom_point(data=station.data,aes(x=LONGITUDE,y=LATITUDE,color=Direction,size=Flux,frame=Group))+
  transition_states(Group)+
  scale_size_continuous(range = c(1, 15))
```

## Map
<div class="centered">
```{r,warnings=FALSE}
suppressWarnings(animate(DC_map_stations, width = 1000, height = 1000,fps=5))
```